name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:  # Triggered by webhooks from repos
    types: [build]
  schedule:
    - cron: "0 * * * *"  # Hourly, can be overridden per repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build --platform linux/s390x . -t zlinux-artifacts-builder

      - name: Run orchestrator
        run: |
          docker run --rm --privileged -v $(pwd):/app -v /var/run/docker.sock:/var/run/docker.sock \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            zlinux-artifacts-builder
